plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
 
url: https://copperi.ru

title: ""

collections:
  catalog:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/dizaynerskiy-radiator-otoplenia-copperi-anisotropia-cu.jpg