plugins:
  - jekyll-seo-tag
  
collections:
  catalog:
    output: true

social:
  name: Veshi
  links:
    - https://www.facebook.com/
    - http://instagram.com/

logo: /images/logo.svg
url:

title: ""
lang: "ru_RU"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/logo.jpg
